---

hostname: rtr-3
domain_name: lab.local

loopback:
  dum0:
    alias: dummy loopback0
    address: 10.255.0.3
    mask: /32

interfaces:
  eth1:
    alias: connection rtr-2
    address: 10.0.253.2
    mask: /30

  eth2:
    alias: conection rtr-1
    address: 10.0.255.6
    mask: /30

  eth3:
    alias: connection rtr-4
    address: 10.0.254.6
    mask: /30

bgp:
  asn: 65000
  neighbor:
    - {address: 10.0.254.5, remote_as: 65002}
    - {address: 10.0.255.5, remote_as: 65001}
  networks:
    - {network: 10.0.254.4, mask: /30}
    - {network: 10.0.255.4, mask: /30}
    - {network: 10.255.0.3, mask: /32}
